from enum import Enum

class BceaoEventType(str, Enum):
    DECLARATION_SOUPCON       = "DECLARATION_SOUPCON"
    CONTROLE_CBF              = "CONTROLE_CBF"
    RAPPORT_MENSUEL_BCEAO     = "RAPPORT_MENSUEL_BCEAO"
    INCIDENT_PAIEMENT         = "INCIDENT_PAIEMENT"
    AGREMENT_BANQUE           = "AGREMENT_BANQUE"
    AGREMENT_MONNAIE_ELEC     = "AGREMENT_MONNAIE_ELEC"
    RATIO_PRUDENTIEL_BREACH   = "RATIO_PRUDENTIEL_BREACH"
    OUVERTURE_COMPTE_KYC      = "OUVERTURE_COMPTE_KYC"
