from enum import Enum


class OhadaEventType(str, Enum):
    CREATION_SARL          = "CREATION_SARL"
    CREATION_SA            = "CREATION_SA"
    AGO_ANNUELLE           = "AGO_ANNUELLE"
    DISSOLUTION            = "DISSOLUTION"
    CESSION_PARTS          = "CESSION_PARTS"
    AUGMENTATION_CAPITAL   = "AUGMENTATION_CAPITAL"
    FUSION_ABSORPTION      = "FUSION_ABSORPTION"
    INJONCTION_PAYER       = "INJONCTION_PAYER"
    REDRESSEMENT_JUDICIAIRE = "REDRESSEMENT_JUDICIAIRE"
    IMMATRICULATION_RCCM   = "IMMATRICULATION_RCCM"
