from enum import Enum

class FiscaliteEventType(str, Enum):
    DECLARATION_TVA          = "DECLARATION_TVA"
    DECLARATION_IS           = "DECLARATION_IS"
    DECLARATION_IRPP         = "DECLARATION_IRPP"
    CONTROLE_FISCAL          = "CONTROLE_FISCAL"
    REDRESSEMENT_FISCAL      = "REDRESSEMENT_FISCAL"
    CONTENTIEUX_FISCAL       = "CONTENTIEUX_FISCAL"
    RETENUE_SOURCE_SALAIRES  = "RETENUE_SOURCE_SALAIRES"
    CREATION_ENTREPRISE_DGI  = "CREATION_ENTREPRISE_DGI"
